config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :cigars
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'cigars#index'
end

app/models/cigar.rb
class Cigar < ApplicationRecord
  mount_uploader :image, ImageUploader
  serialize :image, JSON # If SQLite is used

  belongs_to :user, optional: true
  has_many :line_items

  validates :brand, :origin, :size, :shape, :binder, :filler, :wrapper, :price, presence: true
  validates :description, presence: true, length: { maximum: 255, too_long: '%{count} characters is the maximum allowed.' }
  validates :price, length: { maximum: 7 }

  BRAND = ['Drew Estate', 'Padron', 'My Father', 'Oliva', 'Punch', 'Cohiba', 'Monticristo', 'Roma Craft', 'Davidoff', 'Illusione'].freeze
  WRAPPER = %w[Candela Connecticut Maduro Natural].freeze
  BINDER = %w[Nicuraguan Dominican Sumatran Mexican Honduran Cuban].freeze
  FILLER = %w[Nicuraguan Dominican Sumatran Mexican Honduran Cuban Mixed].freeze
end

app/controllers/cigars_controller.rb
class CigarsController < ApplicationController
  before_action :set_cigar, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /cigars
  # GET /cigars.json
  def index
    @cigars = Cigar.all.order('created_at desc')
  end

  # GET /cigars/1
  # GET /cigars/1.json
  def show; end

  # GET /cigars/new
  def new
    @cigar = current_user.cigars.build
  end

  # GET /cigars/1/edit
  def edit; end

  # POST /cigars
  # POST /cigars.json
  def create
    @cigar = current_user.cigars.build(cigar_params)

    respond_to do |format|
      if @cigar.save
        format.html { redirect_to @cigar, notice: 'Cigar was successfully created.' }
        format.json { render :show, status: :created, location: @cigar }
      else
        format.html { render :new }
        format.json { render json: @cigar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cigars/1
  # PATCH/PUT /cigars/1.json
  def update
    respond_to do |format|
      if @cigar.update(cigar_params)
        format.html { redirect_to cigars_path, notice: 'Cigar was successfully updated.' }
        format.json { render :show, status: :ok, location: @cigar }
      else
        format.html { render :edit }
        format.json { render json: @cigar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cigars/1
  # DELETE /cigars/1.json
  def destroy
    @cigar.destroy
    respond_to do |format|
      format.html { redirect_to cigars_url, notice: 'Cigar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cigar
    @cigar = Cigar.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cigar_params
    params.require(:cigar).permit(:brand, :origin, :description, :size, :shape, :binder, :filler, :wrapper, :price, :image)
  end
end

app/helpers/cigars_helper.rb
module CigarsHelper
  def cigar_author(cigar)
    user_signed_in? && current_user.id == cigar.user_id
  end
end

app/views/cigars/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @cigar, html: { multipart: true } do |f| %>
    <%= f.error_notification %>

    <div class="columns">

      <div class="field column is-6">
        <div class="control">
          <%= f.input :brand , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="field column">
        <div class="control">
          <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7 }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

    </div>

    <div class="field">
      <div class="control">
        <%= f.input :origin, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :shape, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :size, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Brand</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :brand, collection: Cigar::BRAND, prompt: "Select brand" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="field column is-4">
        <div class="control">
          <label class="label">Wrapper</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :wrapper, collection: Cigar::WRAPPER, prompt: "Select wrapper" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="field column is-4">
        <div class="control">
          <label class="label">Binder</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :binder, collection: Cigar::BINDER, prompt: "Select binder" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-paint-brush"></i>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="field column is-4">
      <div class="control">
        <label class="label">Filler</label>
        <div class="control has-icons-left">
          <span class="select">
            <%= f.input_field :filler, collection: Cigar::FILLER, prompt: "Select filler" %>
          </span>
          <span class="icon is-small is-left">
            <i class="fa fa-paint-brush"></i>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="field column is-4">
    <div class="control">
      <label class="label">Add images</label>
      <div class="file">
        <label class="file-label">
          <%= f.input :image, as: :file, input_html: { class:"file-input cigar-image" }, label: false, wrapper: false %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fa fa-upload"></i>
            </span>
            <span class="file-label">Choose a file…</span>
          </span>
        </label>
      </div>
    </div>
  </div>
  <output id="list"></output>
  <hr/>

  <div class="field is-grouped">
    <div class="control">
      <%= f.button :submit, class: 'button is-warning' %>
      <%= link_to 'Cancel', cigars_path, class:'button is-light' %>
    </div>
  </div>

<% end %>
</div>

app/views/cigars/edit.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Edit a Cigar
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', cigar: @cigar %>
</div>

app/views/cigars/index.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Browse the latest cigars
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="cigar-index-grid pt4">
  <% @cigars.each do |cigar| %>
    <div class="cigar border-light">
      <div class="cigar-thumb">
        <%= link_to image_tag(cigar.image_url(:thumb)), cigar %>
        <% if cigar.brand? %>
          <div class="brand">
            <span class="tag is-dark"><%= cigar.brand %></span>
          </div>
        <% end %>
      </div>

      <div class="pa3">
        <h3 class="fw7 f4 title"><%= link_to cigar.brand %></h3>
        <p class="has-text-gray fg pt1">Sold by
          <%= cigar.user.name %></p>
        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(cigar.price) %></p>

        <% if cigar_author(cigar) %>
          <%= link_to 'Edit', edit_cigar_path(cigar), class: "button is-small" %>
          <%= link_to 'Delete', cigar, method: :delete, data: { confirm: "Are you sure you want to delete this cigar?"}, class: "button is-small" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/cigars/new.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Sell a Cigar
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', cigar: @cigar %>
</div>

app/views/cigars/show.html.erb
<%= content_for :body_class, 'bg-light' %>

<section class="section cigar-show">
  <div class="columns">
    <div class="column is-8 has-text-weight-bold">
      <h1 class="title is-2"><%= @cigar.brand %></h1>

      <ul class="pv1 has-text-weight-bold">
        <% if @cigar.brand? && @cigar.origin? %>
          <li class="inline-block pr3"><%= @cigar.brand %>,
            <%= @cigar.origin %></li>
        <% end %>
      </ul>
      <div class="feature-image">
        <%= image_tag(@cigar.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">
        <%= @cigar.description %>

        <h3 class="subtitle is-4 pt5">Cigar Details</h3>

        <table class="table is-narrow">
          <% if @cigar.wrapper %>
            <tr>
              <td class="has-text-weight-bold">Wrapper:</td>
              <td><%= @cigar.wrapper %></td>
            </tr>
          <% end %>

          <% if @cigar.binder %>
            <tr>
              <td class="has-text-weight-bold">Binder:</td>
              <td><%= @cigar.binder %></td>
            </tr>
          <% end %>

          <% if @cigar.filler %>
            <tr>
              <td class="has-text-weight-bold">Filler:</td>
              <td><%= @cigar.filler %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3" id="shopping-div">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@cigar.price) %></h4>
        <p class="has-text-centered mb4">Sold by:
          <%= @cigar.user.name %></p>
        <%= button_to 'Add to Cart', '#', class: "button is-warning add-to-cart" %>
      </div>
    </div>
  </div>

  <% if cigar_author(@cigar) %>
    <%= link_to 'Edit', edit_cigar_path(@cigar), class: 'button' %>
  <% end %>
</section>